#!/bin/bash

for repo in $(ls archive);do
  echo "Attempting to delete repo $repo if it exists"
  if git ls-remote -q git@github.com:samhstn/$repo &> /dev/null;then
    echo "Deleting repo $repo"
    curl -X DELETE -H "Authorization: token $GITHUB_PA_TOKEN" https://api.github.com/repos/samhstn/$repo
  fi
done
